from django.urls import path
from . import views

urlpatterns = [
    path('panel/', views.panel_admin, name='panel_admin'),
    path('publicaciones/', views.panel_publicaciones_admin, name='panel_publicaciones_admin'),
    path('admin-anuncio/', views.crear_anuncio, name='crear_anuncio'),
    path('ver-anuncios/', views.lista_anuncios, name='lista_anuncios'),
    path('anuncios/eliminar/<str:id>/', views.eliminar_anuncio, name='eliminar_anuncio'),
    path('anuncios/editar/<str:id>/', views.editar_anuncio, name='editar_anuncio'),
    path("crear-convocatoria/", views.crear_convocatoria_admin, name="crear_convocatoria"),
    path('convocatoria/editar/', views.editar_convocatoria, name='editar_convocatoria'),
    path('convocatoria/eliminar/', views.eliminar_convocatoria, name='eliminar_convocatoria'),
    path('solicitudes/', views.solicitudes_panel, name='solicitudes_panel'),
    path('solicitud/detalle/', views.detalle_solicitud, name='detalle_solicitud'),
    path("obtener_solicitudes/", views.obtener_solicitudes),
    path("actualizar_estado/<str:id>/", views.actualizar_estado),
    path("contratos/", views.ver_contratos, name="ver_contratos"),
    path("contrato-vigente/", views.contrato_vigente_admin, name="contrato_vigente_admin"),
    path("contrato-vigente/ver/", views.ver_contrato_vigente_admin, name="ver_contrato_vigente_admin"),
    path("contratos/ver/<str:id>/", views.ver_contrato, name="ver_contrato"),
    path("contratos/decidir/<str:id>/", views.confirmar_contrato, name="confirmar_contrato"),
    path("proyectos/", views.proyectos_activos, name="proyectos_activos"),
    path("proyectos/<str:id>/ficha.pdf", views.exportar_ficha_proyecto, name="exportar_ficha_proyecto"),
    path("proyectos/api/", views.proyectos_api, name="proyectos_api"),
    path("proyectos/api/<str:id>/estado/", views.proyecto_cambiar_estado, name="proyecto_cambiar_estado"),
    path("proyectos/api/<str:id>/finalizar/", views.finalizar_proyecto_api, name="finalizar_proyecto_api"),
    path("proyectos/api/<str:id>/eliminar/", views.eliminar_proyecto_api, name="eliminar_proyecto_api"),
    path("expedientes/", views.expedientes_admin, name="expedientes_admin"),
    path("expedientes/descargar/<str:documento_id>/", views.descargar_documento_expediente_admin, name="descargar_documento_expediente_admin"),
    path("expedientes/ver/<str:documento_id>/", views.ver_documento_expediente_admin, name="ver_documento_expediente_admin"),
    path("recursos/", views.recursos_admin, name="recursos_admin"),
    path("recursos/descargar/<str:id>/", views.recurso_descargar_admin, name="recurso_descargar_admin"),
    path("calendario/", views.calendario_admin, name="calendario_admin"),
    path("calendario/api/eventos/", views.calendario_eventos, name="calendario_eventos"),
    path("calendario/api/eventos/<str:id>/", views.calendario_evento_detalle, name="calendario_evento_detalle"),
    path("chats/", views.chat_admin, name="chat_admin"),
    path("chats/api/conversaciones/", views.chat_admin_conversaciones, name="chat_admin_conversaciones"),
    path("chats/api/mensajes/<str:usuario_id>/", views.chat_admin_mensajes, name="chat_admin_mensajes"),
    path("chats/api/enviar/<str:usuario_id>/", views.chat_admin_enviar, name="chat_admin_enviar"),
    path("chats/api/editar/<str:mensaje_id>/", views.chat_admin_editar, name="chat_admin_editar"),
    path("chats/api/eliminar/<str:mensaje_id>/", views.chat_admin_eliminar, name="chat_admin_eliminar"),
    path("chats/api/archivo/<str:mensaje_id>/", views.chat_admin_archivo, name="chat_admin_archivo"),
    path("agregar-administrador/", views.agregar_administrador, name="agregar_administrador"),
    path('admin/crear-admin-api/', views.crear_admin_api, name='crear_admin_api'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('usuarios/bloquear/<str:id>/', views.bloquear_usuario, name='bloquear_usuario'),
    path('usuarios/desbloquear/<str:id>/', views.desbloquear_usuario, name='desbloquear_usuario'),
    path('usuarios/cambiar-estado/<str:id>/', views.cambiar_estado_usuario, name='cambiar_estado_usuario'),
    path('usuarios/password/<str:id>/', views.actualizar_password_usuario, name='actualizar_password_usuario'),
    path('usuarios/eliminar/<str:id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('perfil-admin/', views.perfil_admin, name='perfil_admin'),
    path('admin/password/<str:id>/', views.actualizar_password_admin, name='actualizar_password_admin'),
    path('admin/eliminar/<str:id>/', views.eliminar_admin, name='eliminar_admin'),
    path('recursos/editar/<str:id>/', views.recurso_editar_admin, name='recurso_editar_admin'),
    path('recursos/eliminar/<str:id>/', views.recurso_eliminar_admin, name='recurso_eliminar_admin'),
]
